<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        if (!defined('LARAVEL_START')) {
            define('LARAVEL_START', microtime(true));
        }

    }

    public function signIn($user = null, $driver = null)
    {
        return $this->actingAs($user ?: factory('App\User')->create(), $driver);
    }
}
