<?php

namespace Tests;

use App\Category;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Http\UploadedFile;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        if (!defined('LARAVEL_START')) {
            define('LARAVEL_START', microtime(true));
        }

    }

    public function signIn($user = null, $driver = null)
    {
        return $this->actingAs($user ?: factory('App\User')->create(), $driver);
    }

    public function signInAsCompany($user = null, $driver = null)
    {

        return $this->actingAs($user ?: factory('App\User', [
            'register_as' => 'company',
            'category' => factory(Category::class)->create()->id,
            'location' => '12.23778823,23.2312312'
        ])->create(), $driver);

    }
}
