<?php

namespace Tests\Feature;

use App\Entity;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class EntitiesReviewApiTest extends TestCase
{

    private $user;
    private $entity;

    function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = factory(User::class)->create();

        $this->entity = factory(Entity::class)->create();


    }

    /**
     @test
     */
    public function test_user_can_review_an_entity()
    {

        $this->signIn($this->user, 'api');

        $response = $this->post(route('api.entitiesReviews.store', [
            'entity' => $this->entity->id
        ]), [
            'review' => "This is a very nice entity"
        ]);

        $response->assertStatus(200)->assertJsonFragment([
            "user_id" => $this->user->id,
            "review" => "This is a very nice entity",
            "entity_id" => $this->entity->id
        ]);

    }


//    /**
//    @test
//     */
//    public function test_user_can_delete_review_from_entity()
//    {
//
//        $this->withoutExceptionHandling();
//
//        $this->signIn($this->user, 'api');
//
//        $review = $this->entity->review('This is a very nice entity');
//
//        $response = $this->delete(route('api.entitiesReviews.destroy', [
//            'entity' => $this->entity->id
//        ]), [
//            'review' => $review->id
//        ]);
//
//        $response->assertStatus(200)->assertJsonFragment([
//            "message" => "review deleted"
//        ]);
//
//    }


}
