<?php

namespace Tests\Feature;

use App\Entity;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class RelatedPlaces extends TestCase
{

    use DatabaseMigrations;

    protected function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        factory(Entity::class, 5)->create();


    }

    /** @test */
    public function it_return_related_places_to_the_given_entity()
    {

        /**
         *
         * When I return related places to a given entity then i will get the entities which are created by this
         * entity, that contains the parent as an entity
         * Or the entities that has the same tag
         * Or the entities created by the same user
         * Or the entities that has some commonalities between them
         *
         */

    }

}
