<?php

namespace Tests\Feature;

use App\Tag;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TagsApiTest extends TestCase
{

    private $tags;

    protected function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        $this->tags = factory(Tag::class, 5)->create();

    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testExample()
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }

    /**
    @test
     */
    public function it_should_return_tags() {

        $response = $this->get(route('api.tags.index'));

        $response
            ->assertJsonCount(5, 'data')
            ->assertOk();

    }

    /**
    @test
     */
    public function it_should_search_tags() {

        $response = $this->get(route('api.tags.index', [
            'q' => $this->tags[0]->name
        ]));

        $response
            ->assertJsonCount(2, 'data.0')
            ->assertOk();

    }



}
